# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 19:03
from __future__ import unicode_literals

from django.db import migrations
import uuid


def gen_animals(apps, schema_editor):
    Animal = apps.get_model('testpage', 'Animal')
    for i in range(0, 20):
        gen = uuid.uuid4().hex
        Animal.objects.create(
            family='Dog',
            email_address='{}@dog.com'.format(gen),
            name='Sparky {}'.format(i),
            secret_key=gen
        )


class Migration(migrations.Migration):

    dependencies = [
        ('testpage', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(gen_animals),
    ]
